#!/usr/bin/env bash
# Generate the contents of the PUBLIC add-on repository.
#
# The public repo is a manifest only: no Dockerfile, no src/. The Supervisor
# pulls a prebuilt image from GHCR (config.yaml's `image:` key) instead of
# cloning and building, so the beta source stays in the private repo.
#
# FEM did the opposite — franklinwh-addon bundles 128 source files and 193
# vendored ones — which is why making that repo public would publish FEM's
# source and its whole history along with it.
#
#   ./scripts/make_public_addon_repo.sh [output-dir]
#
# Then review the output and push it as an ORPHAN branch, so none of the
# private history comes with it:
#
#   cd <output-dir>
#   git init && git checkout --orphan main
#   git add -A && git commit -m "FranklinWH HA Integrator add-on"
#   git remote add origin git@github.com:david2069/franklinwh-addon.git
#   git push --force origin main
#
# Toggling visibility is deliberately NOT done here — it is irreversible in
# practice (forks, mirrors and caches persist) and is the maintainer's call.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ADDON="$REPO_ROOT/franklinwh_ha_integrator"
OUT="${1:-$REPO_ROOT/build/public-addon}"
SLUG="franklinwh_ha_integrator"
OWNER="david2069"

VERSION="$(cat "$REPO_ROOT/VERSION")"

rm -rf "$OUT"
mkdir -p "$OUT/$SLUG"

# ── repository descriptor ────────────────────────────────────────────────────
cat > "$OUT/repository.yaml" <<YAML
---
name: FranklinWH Add-ons
url: https://github.com/$OWNER/franklinwh-addon
maintainer: David Hona
YAML

# ── the add-on manifest, with image: instead of a build context ──────────────
# Everything the Supervisor needs to describe and configure the add-on, minus
# anything it would need to build it.
"$REPO_ROOT/.venv/bin/python" - "$ADDON/config.yaml" "$OUT/$SLUG/config.yaml" "$OWNER" "$VERSION" <<'PY'
import sys, yaml

src, dst, owner, version = sys.argv[1:5]
cfg = yaml.safe_load(open(src).read())

# No `image:` key. Its presence makes the Supervisor PULL a prebuilt image;
# without it the Supervisor CLONES this repository and BUILDS on the machine
# it is installed on — no container registry, no package visibility step.
cfg.pop("image", None)
cfg["version"] = version

with open(dst, "w") as fh:
    fh.write(
        "---\n"
        "# Generated by scripts/make_public_addon_repo.sh - do not hand-edit.\n"
        "#\n"
        "# No image: key, so the Supervisor builds this add-on from the source\n"
        "# in this repository rather than pulling a prebuilt image.\n"
    )
    yaml.safe_dump(cfg, fh, sort_keys=False, default_flow_style=False, allow_unicode=True)
print(f"  config.yaml    builds from source, version {version}")
PY

# ── the files a user actually reads ──────────────────────────────────────────
# The full build context. The Supervisor clones this repository and runs a
# docker build against this folder, so everything the Dockerfile COPYs must be
# here - one level up does not exist as far as that build is concerned.
for f in DOCS.md icon.png logo.png Dockerfile run.sh requirements.txt build.yaml VERSION; do
    cp "$ADDON/$f" "$OUT/$SLUG/$f"
done
for d in src scripts db; do
    rsync -a --delete --exclude=__pycache__ --exclude='*.pyc' --exclude=.DS_Store \
        "$ADDON/$d/" "$OUT/$SLUG/$d/"
done
printf '  build context  %s files\n' "$(find "$OUT/$SLUG" -type f | wc -l | tr -d ' ')"

# The changelog is trimmed to the most recent releases.
#
# The Supervisor renders the whole file in the add-on's Changelog tab, and the
# full history is 1,394 lines — a wall nobody scrolls, on a tab people open to
# answer one question: what changed in the version I am being offered?
# The rest stays in the repository, which is linked at the bottom.
"$REPO_ROOT/.venv/bin/python" - "$REPO_ROOT/CHANGELOG.md" "$OUT/$SLUG/CHANGELOG.md" "$OWNER" <<'PY'
import re
import sys

src, dst, owner = sys.argv[1:4]
text = open(src).read()
KEEP = 3   # released versions; [Unreleased] is always kept on top of them

# Release headings look like "## [0.6.0] - 2026-08-07". [Unreleased] matches the
# same shape, so it is counted separately rather than eating one of the slots.
heads = [(m.start(), m.group(1)) for m in re.finditer(r"^## \[([^\]]+)\]", text, re.M)]
released = [h for h in heads if h[1].lower() != "unreleased"]

# Drop an EMPTY [Unreleased] heading. In the repository it is where the next
# change goes; in the add-on's Changelog tab it is a heading with nothing under
# it, sitting above the release the reader actually came for. An [Unreleased]
# with content stays — that is work shipped but not yet versioned, which a
# reader of a just-updated add-on may well be running.
for pos, name in heads:
    if name.lower() != "unreleased":
        continue
    nxt = next((p2 for p2, _ in heads if p2 > pos), len(text))
    body = text[pos + len("## [Unreleased]"):nxt].strip()
    if not body:
        text = text[:pos] + text[nxt:]
        heads = [(m.start(), m.group(1)) for m in re.finditer(r"^## \[([^\]]+)\]", text, re.M)]
        released = [h for h in heads if h[1].lower() != "unreleased"]
    break

if len(released) <= KEEP:
    kept, cut_from = text, None
else:
    cut_from = released[KEEP][0]
    kept = text[:cut_from]

# Keep the file's own preamble — the first heading is where entries start.
# Link to the PUBLIC repository's own copy. Pointing at the source repo would
# 404 for every reader, since it is private — the same trap as the container
# image's source label.
tail = (
    f"\n---\n\nOlder releases: "
    f"[full changelog](https://github.com/{owner}/franklinwh-addon/blob/main/CHANGELOG-full.md)\n"
)
open(dst, "w").write(kept.rstrip() + "\n" + tail)

lines = kept.count("\n")
names = ", ".join(v for _, v in released[:KEEP])
print(f"  CHANGELOG.md   {lines} lines (was {text.count(chr(10))}) — keeping {names}")
PY

# The complete history, for the link at the foot of the trimmed changelog.
# Public-safe: it is prose, and the add-on's Changelog tab renders only the
# trimmed file.
cp "$REPO_ROOT/CHANGELOG.md" "$OUT/CHANGELOG-full.md"
printf '  %-18s %s bytes (full history, linked from the tab)\n' "CHANGELOG-full.md" \
    "$(wc -c < "$OUT/CHANGELOG-full.md" | tr -d ' ')"

# Quoted delimiter: the README contains backticks and must not be
# interpreted by the shell. Placeholders are substituted after.
cat > "$OUT/README.md" <<'MD'
# FranklinWH Add-ons for Home Assistant

Home Assistant add-ons for FranklinWH aGate battery systems.

## Install

1. In Home Assistant, go to **Settings -> Add-ons -> Add-on Store**.
2. Open the **three-dot menu** (top right) -> **Repositories**.
3. Paste this URL and click **Add**:

   ```
   https://github.com/__OWNER__/franklinwh-addon
   ```

4. Close the dialog. **FranklinWH HA Integrator** now appears in the store —
   reload the page if it does not.
5. Click it, then **Install**. The add-on ships as a prebuilt image, so this is
   a download rather than a build: seconds, not minutes.
6. Open **Configuration**, enter your FranklinWH cloud email and password, and
   **Save**.
7. **Start**, then open the UI from the sidebar.

Nothing else is required. MQTT defaults to the Home Assistant Mosquitto add-on,
gateways are discovered from your account, and the add-on runs behind Ingress —
no port to expose and no separate login.

## Add-ons in this repository

### FranklinWH HA Integrator

Bridges one or more FranklinWH aGate battery systems to Home Assistant over
MQTT Discovery: battery and per-aPower telemetry, mode control, manual charge
and discharge, TOU schedule editing with presets and push history, solar
forecasting, and cost tracking against your own tariff.

Full documentation is on the add-on's **Documentation** tab after installing,
or [here](__SLUG__/DOCS.md).

## Requirements

- Home Assistant **OS** or **Supervised** — add-ons are not available on
  Container or Core installs
- Architecture **aarch64** or **amd64**: HA Green, HA Yellow, Raspberry Pi 4/5,
  and any x86 machine or VM. 32-bit builds are not offered — several
  dependencies are Rust, and rustup does not support the musl armv7 target
  triple, so they cannot be built at all.
- A FranklinWH cloud account — the same credentials as the FranklinWH app
- An MQTT broker; the Mosquitto add-on is detected automatically

## Updating

Home Assistant offers an update when a new version is published. Release notes
are on the add-on's **Changelog** tab.

## Support

Issues and feature requests:
<https://github.com/__OWNER__/franklinwh-ha-integrator/issues>

Unofficial. Not affiliated with, endorsed by, or supported by FranklinWH.
MD
sed -i '' -e "s|__OWNER__|$OWNER|g" -e "s|__SLUG__|$SLUG|g" "$OUT/README.md"

echo
echo "  → $OUT"
echo "  $(find "$OUT" -type f | wc -l | tr -d ' ') files, no source"
