#!/usr/bin/env python3
"""Generate docs/cloud_library_defects.md from the cloud library's defect list.

The library records its own defects in `../franklinwh-cloud/defect_list.md`.
Twenty-six of them affect methods this integration calls, and nothing here
mentioned a single one — which is how `set_generator_mode()` came to be used as
a mode setter while upstream documented that it writes a manual start/stop.

Reading that file should not depend on somebody remembering to. This regenerates
the register; `tests/test_cloud_api_surface.py` fails when a defect affecting a
method we call is missing from it.

    python3 scripts/sync_cloud_defects.py

Every entry starts as "not reviewed". That is honest: the defect is recorded,
its effect here is not yet assessed, and the register is a work queue rather
than a claim that everything is handled.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLOUD = ROOT.parent / "franklinwh-cloud" / "defect_list.md"
OUT = ROOT / "docs" / "cloud_library_defects.md"

sys.path.insert(0, str(ROOT))
from tests.test_cloud_api_surface import _call_sites, defect_affects  # noqa: E402


def main() -> int:
    if not CLOUD.exists():
        print(f"cloud defect list not found at {CLOUD}", file=sys.stderr)
        return 1

    called = {m for _p, _l, m in _call_sites()}
    existing = OUT.read_text(encoding="utf-8") if OUT.exists() else ""

    rows = []
    for line in CLOUD.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| DEF-"):
            continue
        cells = [c.strip() for c in line.split("|")[1:-1]]
        if len(cells) < 3:
            continue
        defect_id, area, detail = cells[0], cells[1], cells[2]
        hit = next((m for m in called if defect_affects(line, m)), None)
        if not hit:
            continue
        # Keep a verdict someone has already written.
        prior = re.search(rf"^\| `{re.escape(defect_id)}`.*?\|([^|]*)\|\s*$",
                          existing, re.M)
        verdict = prior.group(1).strip() if prior else "not reviewed"
        summary = re.sub(r"\*\*|\s+", lambda m: "" if m.group().startswith("*") else " ",
                         detail)[:180].strip()
        rows.append((defect_id, hit, area, summary, verdict))

    rows.sort()
    lines = [
        "# Cloud library defects affecting this integration",
        "",
        "Generated by `scripts/sync_cloud_defects.py` from",
        "`../franklinwh-cloud/defect_list.md`. Do not edit the table by hand except",
        "the **Assessed** column, which is preserved across regeneration.",
        "",
        "These are defects the library documents in methods this integration calls.",
        "A defect being listed here does not mean it bites us — it means somebody",
        "should decide, and record the decision. `not reviewed` is a work queue",
        "entry, not a clean bill of health.",
        "",
        "`tests/test_cloud_api_surface.py` fails when a defect affecting a method we",
        "call is absent from this file, so a library release surfaces its delta here",
        "rather than in production.",
        "",
        f"{len(rows)} defects affecting methods called from `src/`.",
        "",
        "| Defect | Method | Area | Summary | Assessed |",
        "|---|---|---|---|---|",
    ]
    for defect_id, method, area, summary, verdict in rows:
        lines.append(f"| `{defect_id}` | `{method}()` | {area} | {summary} | {verdict} |")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"  {OUT.relative_to(ROOT)} — {len(rows)} defects")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
